### ISSUE TITLE
Run on Chrome version that doesn't support import

### ISSUE THREAD

**Issue by JohannBlake** [RobertMenke/rm-emoji-picker#31]
I would like to use your widget but I am running Electron, which uses Chromium version 56. The import statement is not supported in Chrome versions less than 60.

Is there a way that I can get around this?

**Comment by RobertMenke** [comment]
@JohannBlake Yes, there are a few ways. The EmojiPicker module is a UMD module, meaning that it can be loaded in a number of ways including globally in a script tag. https://github.com/umdjs/umd

Here are some ways you can use the module:

1. Use babel and/or webpack to transpile your code. I would highly recommend this approach for larger projects, but I understand if you don't want to get into a build system.
2. Include a script tag in your page and use EmojiPicker as a globally available variable

Let me know if you still have issues. Thanks for the question!

**Comment by JohannBlake** [comment]
@RobertMenke Thanks for the fast feedback. I updated my original post. I only needed to wait for the DOM to complete loading and it worked. But now I get another issue. First, the icons on the picker's header do not show up. They seem to be visible behind the picker. Also, when I click on an emoji, the following exception is generated:

> Uncaught DOMException: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('checkbox') does not support selection.
>     at e.value (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/rm-emoji-picker/dist/EmojiPicker.js:1:10060)
>     at e.value (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/rm-emoji-picker/dist/EmojiPicker.js:1:9901)
>     at e.value (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/rm-emoji-picker/dist/EmojiPicker.js:1:5178)
>     at e.value (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/rm-emoji-picker/dist/EmojiPicker.js:1:4986)
>     at e.value (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/rm-emoji-picker/dist/EmojiPicker.js:6:875)
>     at HTMLSpanElement.<anonymous> (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/rm-emoji-picker/dist/EmojiPicker.js:6:4533)
>     at HTMLSpanElement.dispatch (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/jquery/dist/jquery.js:5206:27)
>     at HTMLSpanElement.elemData.handle (/Users/johann/Work/Dev/Web/Projects/ServetusClient/node_modules/jquery/dist/jquery.js:5014:28)

No emoji is copied over into my input element.

**Comment by RobertMenke** [comment]
Can you post the code you're using to instantiate the picker including where you're loading CSS and JS?

**Comment by JohannBlake** [comment]
I posted too soon. Found my problem and deleted the last post. However, the picker's icons on the header are not showing. They seem to be showing behind the picker. Attached is a png of what I am seeing: [https://goo.gl/td89xJ](https://goo.gl/td89xJ)

**Comment by RobertMenke** [comment]
@JohannBlake No problem. One thing I'd look at is that the icons in my readme are coming from fontawesome. If font awesome is not being loaded neither will the icons. You can use custom icons if you want by overriding the `categories` property in the object passed to the constructor.

**Comment by JohannBlake** [comment]
Font "awesome" is not installed in my app. I also searched your dist files and nothing is there. Does that mean that by default if this font is not installed, no header icons show up? I also checked Google Fonts but there is no "awesome" font available.

**Comment by RobertMenke** [comment]
@JohannBlake Sorry for the confusion on fontawesome. I'm referring to this icon library that is very popular on the web http://fontawesome.io/. As I mentioned, you can use your own icons by overriding the `categories` property, but by default I'm assuming that the fontawesome cdn is included on the page given its ubiquity.

**Comment by JohannBlake** [comment]
In you docs I read:

> I wanted a modern looking emoji picker that worked on all modern browsers (IE 9+), gave me the flexibility to control what happens when an emoji is clicked, came with support for contenteditable elements, and didn't deal with the horrible :colon: syntax we've forced on users that just want to see a smiley face!

You have indicated that you want users to avoid dealing with the colon. It wasn't clear whether this meant that after selecting an emoji in your picker whether the emoji image would show up in the input element or the colon text. At the moment, when I click an emoji, the colon text is copied to the input element. Is this because I don't have the awesomefont installed? If I install the awesome font, will the input field show the emoji image or just the colon text? I believe that html input fields only show text or Unicode emoji characters but it isn't clear what images your picker is providing. Are they providing colon text and/or unicode characters?

**Comment by RobertMenke** [comment]
@JohannBlake No, they're not providing unicode support. Html textarea elements do not support html. This library was designed with an emoji picker and editor that could support both textarea elements and contenteditable divs. If you want your emojis to appear without the :colon: syntax you will have to use an element like `<pre contenteditable="true"></pre>`. 

Windows operating systems don't support emoji as characters period, so I'm inserting them as images into contenteditable elements the same way that the whatsapp web experience does.

**Comment by JohannBlake** [comment]
I don't have a problem sticking with colon text. Slack users are use to it. Eventually I will provide support for it. Thanks for the tip on how to do it.

Without diving into your code, are the emoji images pngs? I doubt that they are vector images. That means that they would not scale if I choose to set the image size. Well, they would scale but lose resolution. Scaling emojis may not be popular at the moment, but Google did release their chat app last year that does allow for resizing the emojis when pasted into a chat message.

**Comment by JohannBlake** [comment]
I installed the Fontawesome and it now shows. Thanks for the help.

One issue I notice is that if the picker is bound to a container that is at the very bottom of the browser, it will not show. It seems that you designed it to be used by input fields that are much higher up in the browser window where there is enough room below it to display the entire picker. Is that true?

**Comment by RobertMenke** [comment]
@JohannBlake Glad it's working for you now :). One limitation of my positioning library is that the container must be use `position: absolute;` or `position: relative;`. It doesn't matter where on the page that container is, but my positioning algorithm requires either one of those CSS properties at the moment. See https://github.com/RobertMenke/Tooltip-js.

**Comment by JohannBlake** [comment]
I've almost got it to work. See the attached image: [https://goo.gl/Bo79hQ](https://goo.gl/Bo79hQ)

I'm using a div at the bottom the browser that extends from the far left all the way to the far right. I set the picker's container to that div. Notice that the picker is moved way over to the far left and most of it is cut off. I did set the div to relative and that did make a difference as you have indicated. Interestingly, when my div is at the top of the browser, the picker does show to the far left but is not cut off. Any idea what could be causing this. The button that the user will click on to show the picker will be at the bottom far right.

**Comment by JohannBlake** [comment]
I was able to get it to work at the bottom right. I did have to add the icon that you click on to show the picker. Using just the div as shown in the image would not work.

**Comment by JohannBlake** [comment]
The only bug I see at this point is that some emojis are showing the male/female symbol next to them and are not actually part of the emoji: [https://goo.gl/9yH8Ux](https://goo.gl/9yH8Ux)

I suspect that some of these symbols have a property that indicates whether they are male or female and somehow your code is missing that information and male/female symbol gets shown.

**Comment by RobertMenke** [comment]
Interesting, which operating system are you on and which font are you using on your web page?

**Comment by JohannBlake** [comment]
I'm using the latest MacBook Pro running Sierra 10.12.2

**Comment by neverthemachineforever** [comment]
Just on the original issue, I'm considering using this library on an existing project which is a few years old and unfortunately isn't set up for transpiling.

I'm a bit unfamiliar with webpack but what I've done for now (locally) is modified webpack.config.js to expose the output on the window object:
```
    output   : {
        path    : './dist/',
        filename: '[name].js',
        library: 'EmojiPicker',
        libraryTarget: 'var'
    },
```
and also had to modify the case of the jquery external as a requirement
```
    externals: {
        "jquery" : "jQuery"
    }
```

Do you think it's worth considering outputing two dists one for 'umd' and one for 'var' for users with older setups?

Great work on this project by the way 💛

**Comment by RobertMenke** [comment]
@neverthemachineforever Ya I think that would be worthwhile. In my last PR I cleaned up the webpack files significantly. I can throw something together for people that want to use script tags and load `EmojiPicker` as a global variable.

**Comment by RobertMenke** [comment]
@JohannBlake I would imagine that is due to the font being used. In my example `examples/index.html` I did not see that same behavior. 

For now, I'm just using the emoji characters on computers that support emoji natively. In the future, to enforce consistency around these font issues I'll likely just convert all of the emojis to images all of the time. This would also open up support for choosing which style of emoji you wanted.

**Comment by JohannBlake** [comment]
@RobertMenke I'm sure that it does not have anything to do with the font being used as I removed references to all my fonts and used whatever the default font is. This appears to be how well the browser supports this. If I run your example, it shows correctly in Chrome version 59. But my Electron app is using Chrome 56 and it doesn't work there.

**Comment by RobertMenke** [comment]
@JohannBlake I think the only real solution then is for me to rely only on the image representation of the emojis. I'll have to get a PR ready for that.

Thanks for catching this and bringing it up. I'll leave this issue open until I get that PR ready.

**Comment by JohannBlake** [comment]
@RobertMenke I think using the unicode emojis makes more sense because of the significant reduction in bandwidth transmitting these over the Internet. Chrome normally updates itself regularly, although I just updated mine from 59 to 60. Electron though tends to lag behind several versions and it's not used anywhere at the same level as Chrome.

**Comment by RobertMenke** [comment]
@JohannBlake Good point. Perhaps I'll add a setting as part of the object passed to the constructor. Something like `use_unicode_when_possible : boolean` would work fine. 

The issue is that I do want to support the selection of different emoji styles like twitter, emojione, google, etc which does require using images only.
